### ISSUE TITLE
(Q107) Cloud storage type

### ISSUE THREAD

**Issue by guilherme-n-l** [Ditectrev/Google-Cloud-Platform-GCP-Associate-Cloud-Engineer-Practice-Tests-Exams-Questions-Answers#3]
Minimum storage duration for coldline storage is 3 months, for nearline its 30 days. Coldline should be a more cost-efficient solution.

**Comment by danieldanielecki** [comment]
> Minimum storage duration for coldline storage is 3 months, for nearline its 30 days. Coldline should be a more cost-efficient solution.

Please submit PR 🙏

**Comment by danieldanielecki** [comment]
Please check the comment https://github.com/Ditectrev/Google-Cloud-Platform-GCP-Associate-Cloud-Engineer-Practice-Tests-Exams-Questions-Answers/pull/5#issuecomment-2443275568.
